### ISSUE TITLE
The AutocompleteTextView does not bind the site search value. So you are forced to add a text box to add the search result.

### ISSUE THREAD

**Issue by Yonhe** [megaacheyounes/siteautocomoplete#1]

**Comment by megaacheyounes** [comment]
Hi @Yonhe, this issue is not clear enough, can you provide more details, code snippets (java and xml), and explain in details what you expect the result to be.

**Comment by Yonhe** [comment]
For example After searching, on selecting the search result of interest, it doesnt add the searched target(place) to the AutoCompleteTextView. The AutocompleteTextview still shows "Search sites…" rather. Pls help us on how to set selected value to the search Box(AutoCompleteTextView). Thanks.

**Comment by megaacheyounes** [comment]
Unfortunately, this is not implemented, I will add this feature as soon as I can.

**Comment by megaacheyounes** [comment]
New version have been released with the requested enhancement,
please update to version 1.0.5
```kotlin
dependencies {
	        implementation 'com.github.megaacheyounes:siteautocomoplete:1.0.5'
	}
```

then call `showSelectedSiteOnSearchView(showFullAddress:boolean)`:        
```kotlin
       autocompleteFragment.showSelectedSiteOnSearchView(true)
```
